Feature/rlp-703/invoicing
rsksmart/lumino-web pull request #8
Opened 2020-08-12 18:49 UTC by TheLagger69

Changes:
- Add invoicing to web ui

2020-08-12 20:12 UTC, mauricioirace commented on src/actions/paymentsActions.js
> +    new Promise((resolve, reject) =>
I think this Promise is unnecessary, and makes the functions a bit extra-verbose

2020-08-12 20:12 UTC, mauricioirace commented on src/components/billing/InvoiceForm.jsx
> +export default class InvoiceForm extends Component {
Being this a stateless component, I think a functional component would be more suitable, but it's fine anyway

2020-08-12 20:12 UTC, mauricioirace commented on .gitignore
> +public/static/endpointConfig.js
Why was this file removed?

2020-08-12 20:12 UTC, mauricioirace commented on src/containers/payments/QuickPayment.jsx
> +    const { invoicePayment } = { ...this.props };
Isn't this the same as: `const { invoicePayment } = this.props;` ?

2020-08-13 02:11 UTC, marcosmartinez7 requested changes
Lgtm in general, just some minor changes.

Also, can you put a quick video on the PR description showing this three cases working?:

- Invoice payment
- p2p payment
- Mediated payment

2020-08-13 02:11 UTC, marcosmartinez7 commented on .gitignore
> +public/static/endpointConfig.js
This must not be ignored. It must be ignored only on the node, because its autogenerated on each run, but not in the web proyect.

2020-08-13 02:11 UTC, marcosmartinez7 commented on .gitignore
> +public/static/endpointConfig.js
Also, it must not be removed

2020-08-13 02:11 UTC, marcosmartinez7 commented on src/actions/paymentsActions.js
> +    new Promise((resolve, reject) =>
Yeah me too, we should improve this in the short time, because there are other functions that handle the async calls like this too

2020-08-13 02:11 UTC, marcosmartinez7 commented on src/components/billing/InvoiceForm.jsx
> +export default class InvoiceForm extends Component {
Yeah, i like the idea of having all the components defined exactly the same way. But as a function is ok too.

2020-08-13 02:11 UTC, marcosmartinez7 commented on src/containers/payments/QuickPayment.jsx
> +    const { invoicePayment } = { ...this.props };
Yep, its redundant to clone the right side

2020-08-13 02:11 UTC, marcosmartinez7 commented on src/restClient/index.js
> +  baseURL: isDevelopment() ? "http://localhost:5002" : window.luminoUrl
This must not be modified, 5001 looks good as default port

2020-08-17 18:14 UTC, marcosmartinez7 requested changes
Thanks for de videos. There are some things left:

1. This prs affects the QuickPayment component too, that component is on the header, near the notification buttom, did you test that? 
2. Can you put a video about that functionallity?
3. There are some LGTM bot warnings to fix

2020-08-17 18:15 UTC, marcosmartinez7 commented
test

2020-08-17 20:00 UTC, TheLagger69 commented
> Thanks for de videos. There are some things left:
> 
> 1. This prs affects the QuickPayment component too, that component is on the header, near the notification buttom, did you test that?
> 2. Can you put a video about that functionallity?
> 3. There are some LGTM bot warnings to fix

I've just added a video showing QuickPayment functionality, as fixed LGTM warnings

2020-08-18 13:04 UTC, marcosmartinez7 approved these changes

2020-08-18 13:26 UTC, merged